// ----- ESTRUCTURA GEOGRAFICA DE LA EMPRESA ------ 

// TABLA DE HISTORIAL DE LAS REGIONES
CREATE TABLE Region(
    region_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_region VARCHAR2(50) NOT NULL UNIQUE
);

// TABLA DE HISTORIAL DE LOS PAISES
CREATE TABLE Pais(
    pais_id CHAR(2) PRIMARY KEY,
    nombre_pais VARCHAR2(50) NOT NULL,
    region_id NUMBER,
    
    CONSTRAINT FK_PAIS_REGIONID FOREIGN KEY (region_id) REFERENCES Region(region_id)
);

// TABLA DE HISTORIAL DE LOCALIZACIONES
CREATE TABLE Localizacion(
    localizacion_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calle VARCHAR2(50),
    codigo_postal VARCHAR2(20),
    ciudad VARCHAR2(20),
    provincia VARCHAR(20),
    pais_id CHAR(2) ,
    
    CONSTRAINT FK_LOCALIZACION_PAISID FOREIGN KEY (pais_id) REFERENCES Pais(pais_id)
);


-- Forma de la Organizacion de la Empresa
-- TABLA DE HISTORIAL DE PUESTOS
CREATE TABLE Puesto(
    puesto_id VARCHAR2(10) PRIMARY KEY,
    titulo_puesto VARCHAR2(50) NOT NULL,
    salario_min NUMBER(8,2),
    salario_max NUMBER(8,2),
    
    CONSTRAINT CHK_PUESTOS_SALARIO CHECK(salario_max >= salario_min)
);

-- TABLA DE HISTORIAL DE DEPARTAMENTOS
CREATE TABLE Departamento(
    departamento_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_departamento VARCHAR2(50) NOT NULL UNIQUE,
    manager_id NUMBER,
    localizacion_id NUMBER,
    -- Despues se hara la FOREING KEY de manager_id mediante un ALTER TABLE ya que primero se debe
    -- crear la tabla departamentos ya que cada empleado debe estar en algun departamento para de 
    -- esa forma se puede asignar algun jefe de departamento
    CONSTRAINT FK_DEPARTAMENTO_LOCALIZACIONID FOREIGN KEY (localizacion_id) REFERENCES Localizacion(localizacion_id)
);

-- ESTRUCTURA DE LOS EMPLEADOS DE LA EMPRESA
-- TABLA DE LOS EMPLEADOS
CREATE TABLE Empleado(
    empleado_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    apellido VARCHAR2(50)NOT NULL,
    email VARCHAR2(50) NOT NULL UNIQUE,
    telefono VARCHAR2(50),
    fecha_contratacion DATE NOT NULL,
    salario NUMBER(8,2) NOT NULL,
    comision_pct NUMBER(2,2),
    puesto_id VARCHAR2(10),
    departamento_id NUMBER,
    manager_id NUMBER,
    
    CONSTRAINT EMP_SALARIO_CHECK CHECK(salario > 0),
    CONSTRAINT FK_EMP_PUESTO FOREIGN KEY (puesto_id) REFERENCES Puesto(puesto_id),
    CONSTRAINT FK_EMP_DEPARTAMENTO FOREIGN KEY (departamento_id) REFERENCES Departamento(departamento_id),
    CONSTRAINT FK_EMP_MANAGER FOREIGN KEY (manager_id) REFERENCES Empleado(empleado_id)
);
// TABLA DE HISTORIAL DE PUESTOS
CREATE TABLE Historial_Puesto(
    empleado_id NUMBER,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    puesto_id VARCHAR2(10),
    departamento_id NUMBER,
    
    CONSTRAINT PK_HISTORIAL PRIMARY KEY(empleado_id,fecha_inicio),
    CONSTRAINT FK_EMP_EMPLEADOID FOREIGN KEY (empleado_id) REFERENCES Empleado(empleado_id),
    CONSTRAINT FK_HIS_EMP_PUESTO FOREIGN KEY (puesto_id) REFERENCES Puesto(puesto_id),
    CONSTRAINT FK_HIS_EMP_DEPARTAMENTO FOREIGN KEY (departamento_id) REFERENCES Departamento(departamento_id)
);

-- ESTRUCTURA DE LOS PROYECTOS DE LA EMPRESA
-- TABLA DE HISTORIAL DE PROYECTO
CREATE TABLE Proyecto(
    proyecto_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_proyecto VARCHAR2(100) NOT NULL UNIQUE,
    presupuesto NUMBER(8,2) NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE ,
    
    CONSTRAINT CHK_PROYECTO_PRESUPUESTO CHECK(presupuesto > 0),
    CONSTRAINT CHK_PROYECTO_FECHA CHECK(fecha_fin > fecha_inicio)
);

-- TABLA DE HISTORIAL DE ASIGNACIONES 
CREATE TABLE Asignacion(
    empleado_id NUMBER,
    proyecto_id NUMBER,
    horas_asignadas NUMBER(5,2),
    rol_en_proyecto VARCHAR(50),
    
    CONSTRAINT PK_ASIGNACION PRIMARY KEY (empleado_id,proyecto_id),
    CONSTRAINT FK_ASIGNACION_EMP FOREIGN KEY (empleado_id) REFERENCES Empleado(empleado_id),
    CONSTRAINT FK_ASIGNACION_PROYECTO FOREIGN KEY (proyecto_id) REFERENCES Proyecto(proyecto_id)
);

-- Aqui se agrega la clave foranea de departamento hacia empleados
ALTER TABLE Departamento ADD CONSTRAINT FK_DEPARTAMENTO_MANAGER FOREIGN KEY (manager_id) REFERENCES Empleado(empleado_id);



