-- 1. LIMPIEZA PREVENTIVA (Evitar error si se corre más de una vez)
DROP PROCEDURE sp_registrar_log;
DROP TABLE AUDITORIA_EMPLEADOS CASCADE CONSTRAINTS;
DROP TABLE LOG_ERRORES CASCADE CONSTRAINTS;

-- 2. CREACIÓN DE TABLAS (Sin prefijos, directo en la cuenta adminProyecto)
CREATE TABLE LOG_ERRORES (
    id_log NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    usuario VARCHAR2(50) DEFAULT USER,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    codigo_error NUMBER,
    mensaje_error VARCHAR2(4000)
) TABLESPACE USERS;

CREATE TABLE AUDITORIA_EMPLEADOS (
    id_auditoria NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    usuario VARCHAR2(50) DEFAULT USER,
    fecha_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    accion VARCHAR2(20), -- INSERT o UPDATE
    empleado_id NUMBER,
    salario_anterior NUMBER(8,2),
    salario_nuevo NUMBER(8,2),
    puesto_anterior VARCHAR2(10),
    puesto_nuevo VARCHAR2(10)
) TABLESPACE USERS;

-- 3. PROCEDIMIENTO AUTÓNOMO
CREATE OR REPLACE PROCEDURE sp_registrar_log (
    p_codigo IN NUMBER,
    p_mensaje IN VARCHAR2
) AS
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    INSERT INTO LOG_ERRORES (codigo_error, mensaje_error)
    VALUES (p_codigo, p_mensaje);
    COMMIT;
END;
/